development:
  adapter: postgresql
  encoding: unicode
  database: dialer
  port: 5432
  username: 'postgres'
  password: 'root'
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: dialer
  port: 5432
  username: 'postgres'
  password: 'root'
  #host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: dialer
  port: 5432
  username: 'postgres'
  password: 'root'
  #host: localhost